export const actionType = {
  REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS",
  REGISTRATION_ERROR: "REGISTRATION_ERROR",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  TOKEN_FORM: "TOKEN_FORM",
}
